### ISSUE TITLE
Image Recognition - Format of image CSV File

### ISSUE THREAD

**Issue by telelu03** [ASAAR/SE2-KaggleComp#141]
Okay working on the module to translate my array of numpyarrays into a CSV format that you all can work with

This is what I was thinking of doing:
- Each row represents the info for one image, total number of rows are the total number of images that we're working with
- Each column contains the info for a location, and the pixel info for that location
- For example, the first 3 columns would contain the R, G, and B info for the pixel at 0,0
- The next 3 columns would contain the R, G, B information for the pixel at 0,1

So, for an image with size 90x90, each image would have 8100 * 3  (for RBG values)= 24,300 entries. The larger the image, the more this gets out of hand, so I'll be using very small images in my examples and testing

Does this format seem good to you all? And also, how would you all want me to handle headers? I included a real quick example file of how I would want the end result to look

[exampleformat.xlsx](https://github.com/ASAAR/SE2-KaggleComp/files/622425/exampleformat.xlsx)

**Comment by asclines** [comment]
Overall looks good, I like the idea.
Question: What do you mean by handling headers?  Are you asking whether or not to put them in the csv?

**Comment by telelu03** [comment]
Yes, whether or not we should include them in the CSV or not. I like them just cause they help me understand whats going on, but I don't know if the modules you all have created would want headers

**Comment by asclines** [comment]
Well following this path I would think that either way doesn't make a _huge_ difference. If you leave the headers it, it would me more human readable as you imply, we would just have to make sure that any code that uses it accounts for the headers. 

But what if we did things a little differently. Loading the CSV file would be the same everytime, so instead of doing that what if we have a file reader that takes in the csv file and returns a tensor holding all the information.

**Comment by ASAAR** [comment]
This might work for smaller datasets, however if you have 3GB of images or more, having it in a CSV will not work. That's why many image related problems use file paths to organize training/testing and the labeling of what type each image is. Although I think it's worth supporting both, I want to make sure that the issue is considered.

**Comment by asclines** [comment]
@ASAAR well not _all_ the images have to be in the CSV file at a time.

**Comment by ASAAR** [comment]
Yeah that could be a good middle ground. But the inefficiency of CSVs might be worth investigating. How much extra space does it cost to store in CSV?

**Comment by asclines** [comment]
What other options are you considering? Seeing as the CSVs will be stored on storage, we don't have to worry about memory use. And when the CSV is loaded into memory, I'm willing to bet that it will always take up less space than the images that were loaded into memory earlier to create the CSV.

**Comment by telelu03** [comment]
@ASAAR yeah that's a good point too. If all else fails, I could make multiple CSVs, but size of both the image and the number of images is the biggest issue. But everything will be stored in memory

@asclines I'm not too familiar with the Tensor format...how does it work?

**Comment by asclines** [comment]
The Torch library has pretty good implementation and explanation of using tensors with image processing.

[They explain it pretty well](https://github.com/torch/torch7/blob/master/doc/tensor.md#tensor) 


[Here](https://github.com/torch/image/blob/master/doc/saveload.md) is some good documentation on using a tensor.

**Comment by telelu03** [comment]
lol I keep on mistaking memory for disk. You're right, the CSVs are saved to disk, not memory. My fault lol
